# Preprocessamento dos dados

In [ ]:
#Pacote de dados
import pandas as pd
import numpy as np

In [2]:
#importa dados
list_names = ["Class","AGE","SEX","STEROID","ANTIVIRALS","FATIGUE","MALAISE","ANOREXIA","LIVER BIG","LIVER FIRM","SPLEEN PALPABLE","SPIDERS","ASCITES","VARICES","BILIRUBIN",
              "ALK PHOSPHATE","SGOT","ALBUMIN","PROTIME","HISTOLOGY"]
df = pd.read_csv(r"C:\Users\Alex\Desktop\Aprendizado_de_Maquina\Atividade_01\Hepatite\hepatitis.data", sep=",", names = list_names)

In [3]:
#Visualiza top 10
df.head(n=10)

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
5,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1
6,1,51,1,1,2,1,2,1,2,2,1,1,2,2,?,?,?,?,?,1
7,2,23,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,?,?,?,1
8,2,39,1,2,2,1,2,2,2,1,2,2,2,2,0.70,?,48,4.4,?,1
9,2,30,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,120,3.9,?,1

In [4]:
#Filtra X e Y
y = df.iloc[:,0]
X = df.iloc[:,1:21]

In [5]:
#X.describe()

In [6]:
#Tipo dos dados
pd.DataFrame(X.dtypes).T

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,int64,int64,object,int64,object,object,object,object,object,object,object,object,object,object,object,object,object,object,int64

In [7]:
#Substitui '?' por valor nulo
X.replace('?',np.nan, inplace = True)

In [8]:
pd.DataFrame(X).T

,0,1,2,3,4,5,6,7,8,9,...,145,146,147,148,149,150,151,152,153,154
AGE,30,50,78,31,34,34,51,23,39,30,...,31,41,70,20,36,46,44,61,53,43
SEX,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
STEROID,1,1,2,NaN,2,2,1,2,2,2,...,1,2,1,1,2,2,2,1,1,2
ANTIVIRALS,2,2,2,1,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
FATIGUE,2,1,1,2,2,2,1,2,1,2,...,1,1,1,2,2,1,1,1,1,1
MALAISE,2,2,2,2,2,2,2,2,2,2,...,2,2,1,2,2,1,2,1,2,2
ANOREXIA,2,2,2,2,2,2,1,2,2,2,...,2,2,1,2,2,1,2,2,2,2
LIVER BIG,1,1,2,2,2,2,2,2,2,2,...,2,2,NaN,2,2,2,2,1,2,2
LIVER FIRM,2,2,2,2,2,2,2,2,1,2,...,2,1,NaN,NaN,2,2,1,1,2,2
SPLEEN PALPABLE,2,2,2,2,2,2,1,2,2,2,...,2,1,NaN,2,2,2,2,2,1,1
SPIDERS,2,2,2,2,2,2,1,2,2,2,...,2,1,NaN,2,2,1,2,1,1,1
ASCITES,2,2,2,2,2,2,2,2,2,2,...,2,2,NaN,2,2,1,2,2,2,1
VARICES,2,2,2,2,2,2,2,2,2,2,...,2,1,NaN,2,2,1,2,2,1,2
BILIRUBIN,1.00,0.90,0.70,0.70,1.00,0.90,NaN,1.00,0.70,1.00,...,1.20,4.20,1.70,0.90,0.60,7.60,0.90,0.80,1.50,1.20
ALK PHOSPHATE,85,135,96,46,NaN,95,NaN,NaN,NaN,NaN,...,75,65,109,89,120,NaN,126,75,81,100
SGOT,18,42,32,52,200,28,NaN,NaN,48,120,...,173,120,528,152,30,242,142,20,19,19
ALBUMIN,4.0,3.5,4.0,4.0,4.0,4.0,NaN,NaN,4.4,3.9,...,4.2,3.4,2.8,4.0,4.0,3.3,4.3,4.1,4.1,3.1
PROTIME,NaN,NaN,NaN,80,NaN,75,NaN,NaN,NaN,NaN,...,54,NaN,35,NaN,NaN,50,NaN,NaN,48,42
HISTOLOGY,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2

In [9]:
X['ANTIVIRALS'].unique()

array([2, 1], dtype=int64)

In [10]:
#Preenche os nulos de toda a tabela com a media desconsiderando os nulos, aplica direto
X.fillna( X.median(skipna = True ), inplace = True)

In [11]:
X.T

,0,1,2,3,4,5,6,7,8,9,...,145,146,147,148,149,150,151,152,153,154
AGE,30,50,78,31,34,34,51,23,39,30,...,31,41,70,20,36,46,44,61,53,43
SEX,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
STEROID,1,1,2,2,2,2,1,2,2,2,...,1,2,1,1,2,2,2,1,1,2
ANTIVIRALS,2,2,2,1,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
FATIGUE,2,1,1,2,2,2,1,2,1,2,...,1,1,1,2,2,1,1,1,1,1
MALAISE,2,2,2,2,2,2,2,2,2,2,...,2,2,1,2,2,1,2,1,2,2
ANOREXIA,2,2,2,2,2,2,1,2,2,2,...,2,2,1,2,2,1,2,2,2,2
LIVER BIG,1,1,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,1,2,2
LIVER FIRM,2,2,2,2,2,2,2,2,1,2,...,2,1,2,2,2,2,1,1,2,2
SPLEEN PALPABLE,2,2,2,2,2,2,1,2,2,2,...,2,1,2,2,2,2,2,2,1,1
SPIDERS,2,2,2,2,2,2,1,2,2,2,...,2,1,2,2,2,1,2,1,1,1
ASCITES,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,1,2,2,2,1
VARICES,2,2,2,2,2,2,2,2,2,2,...,2,1,2,2,2,1,2,2,1,2
BILIRUBIN,1.00,0.90,0.70,0.70,1.00,0.90,1,1.00,0.70,1.00,...,1.20,4.20,1.70,0.90,0.60,7.60,0.90,0.80,1.50,1.20
ALK PHOSPHATE,85,135,96,46,85,95,85,85,85,85,...,75,65,109,89,120,85,126,75,81,100
SGOT,18,42,32,52,200,28,58,58,48,120,...,173,120,528,152,30,242,142,20,19,19
ALBUMIN,4.0,3.5,4.0,4.0,4.0,4.0,4,4,4.4,3.9,...,4.2,3.4,2.8,4.0,4.0,3.3,4.3,4.1,4.1,3.1
PROTIME,61,61,61,80,61,75,61,61,61,61,...,54,61,35,61,61,50,61,61,48,42
HISTOLOGY,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2

In [12]:
from sklearn import preprocessing

In [13]:
#
Scaler =preprocessing.StandardScaler()
X.iloc[:,[0,13,14,15,16,17]] = Scaler.fit_transform(X.iloc[:,[0,13,14,15,16,17]] )

In [14]:
X.T

,0,1,2,3,4,5,6,7,8,9,...,145,146,147,148,149,150,151,152,153,154
AGE,-0.894192,0.702579,2.93806,-0.814353,-0.574838,-0.574838,0.782418,-1.45306,-0.175645,-0.894192,...,-0.814353,-0.0159677,2.29935,-1.69258,-0.41516,0.383225,0.223548,1.5808,0.942095,0.143709
SEX,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
STEROID,1,1,2,2,2,2,1,2,2,2,...,1,2,1,1,2,2,2,1,1,2
ANTIVIRALS,2,2,2,1,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
FATIGUE,2,1,1,2,2,2,1,2,1,2,...,1,1,1,2,2,1,1,1,1,1
MALAISE,2,2,2,2,2,2,2,2,2,2,...,2,2,1,2,2,1,2,1,2,2
ANOREXIA,2,2,2,2,2,2,1,2,2,2,...,2,2,1,2,2,1,2,2,2,2
LIVER BIG,1,1,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,1,2,2
LIVER FIRM,2,2,2,2,2,2,2,2,1,2,...,2,1,2,2,2,2,1,1,2,2
SPLEEN PALPABLE,2,2,2,2,2,2,1,2,2,2,...,2,1,2,2,2,2,2,2,1,1
SPIDERS,2,2,2,2,2,2,1,2,2,2,...,2,1,2,2,2,1,2,1,1,1
ASCITES,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,1,2,2,2,1
VARICES,2,2,2,2,2,2,2,2,2,2,...,2,1,2,2,2,1,2,2,1,2
BILIRUBIN,-0.346128,-0.430351,-0.598796,-0.598796,-0.346128,-0.430351,-0.346128,-0.346128,-0.598796,-0.346128,...,-0.177683,2.349,0.243431,-0.430351,-0.683018,5.21257,-0.430351,-0.514573,0.0749853,-0.177683
ALK PHOSPHATE,-0.352069,0.713349,-0.117677,-1.1831,-0.352069,-0.138986,-0.352069,-0.352069,-0.352069,-0.352069,...,-0.565153,-0.778237,0.159332,-0.266836,0.393724,-0.352069,0.521574,-0.565153,-0.437303,-0.0324437
SGOT,-0.760716,-0.488927,-0.602173,-0.375682,1.30035,-0.647471,-0.307735,-0.307735,-0.42098,0.394386,...,0.994586,0.394386,5.01479,0.756771,-0.624822,1.77598,0.643526,-0.738067,-0.749392,-0.749392
ALBUMIN,0.265479,-0.544545,0.265479,0.265479,0.265479,0.265479,0.265479,0.265479,0.913498,0.103474,...,0.589488,-0.70655,-1.67858,0.265479,0.265479,-0.868554,0.751493,0.427483,0.427483,-1.19256
PROTIME,-0.0282253,-0.0282253,-0.0282253,1.08009,-0.0282253,0.788426,-0.0282253,-0.0282253,-0.0282253,-0.0282253,...,-0.436551,-0.0282253,-1.54486,-0.0282253,-0.0282253,-0.66988,-0.0282253,-0.0282253,-0.786545,-1.13654
HISTOLOGY,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2

-----------

# Regressao Logistica - Toolbox

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix

In [16]:
Logit = LogisticRegression()

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33 , random_state=42)

In [18]:
Logit.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
y_pred = Logit.predict(X_test)

In [20]:
y_pred_prob = Logit.predict_proba(X_test)

In [21]:
round(log_loss(y_test, y_pred_prob),3)

0.484

In [22]:
Logit.score(X_test, y_test)

0.8269230769230769

In [23]:
cm = confusion_matrix(y_test,y_pred)

In [24]:
cm

array([[ 3,  7],
       [ 2, 40]], dtype=int64)

----------------

# Classificação Linear

Calculos matriciais

In [49]:
y = np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [52]:
X = np.array([[1,2,7],     [2,3,9],     [2,4,3],     [5,6,1]])
X

array([[1, 2, 7],
       [2, 3, 9],
       [2, 4, 3],
       [5, 6, 1]])

In [53]:
X_T = X.transpose()
X_T

array([[1, 2, 2, 5],
       [2, 3, 4, 6],
       [7, 9, 3, 1]])

In [54]:
X_Mult = X_T.dot(X)
X_Mult

array([[ 34,  46,  36],
       [ 46,  65,  59],
       [ 36,  59, 140]])

In [56]:
df_inv = np.linalg.inv(X_Mult)
df_inv

array([[ 0.94057583, -0.72246401,  0.06260462],
       [-0.72246401,  0.579846  , -0.05858721],
       [ 0.06260462, -0.05858721,  0.01573485]])

In [58]:
pseudo_inv = df_inv.dot(X_T)

In [64]:
omega = pseudo_inv.dot(y)
omega

array([-0.25159022,  0.89052561, -0.03916974])

In [65]:
F_x = omega*X
F_x

array([[-0.25159022,  1.78105122, -0.27418815],
       [-0.50318045,  2.67157683, -0.35252762],
       [-0.50318045,  3.56210244, -0.11750921],
       [-1.25795112,  5.34315367, -0.03916974]])

In [74]:
H_x = np.where( (F_x).sum(axis=1) >2,1,0)
H_x

array([0, 0, 1, 1])

In [87]:
Acuracia = H_x.sum() / H_x.shape[0] 
Acuracia

0.5

# FIM